name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directory to upload
        server-dir: /peacemathew.com.ng/htdocs/kiana-ai  # Adjust to your InfinityFree directory
